### Install Numpy

```
$ pip3 install numpy
```

In [112]:
print("Numpy is awesome.")

Numpy is awesome.


In [5]:
import numpy as np

In [6]:
np.__version__

'1.22.4'

## What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [117]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [123]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
c = []
a[0] + b[0]

4

In [127]:
c = []
c.append(1)
c
c.append(2)
c

[1, 2]

In [119]:
# Normal Python 

a = [1,2,3,4,5]
b = [5,4,3,2,1]

# add element to element
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
    print(c)
    
# print(c)

[6]
[6, 6]
[6, 6, 6]
[6, 6, 6, 6]
[6, 6, 6, 6, 6]


In [131]:
# Numpy array

a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

c = a / b
print(c)

[0.2 0.5 1.  2.  5. ]


### Numpy array creation

- 1D or 1 Dimensional

In [133]:
a = np.array([2, 3, 4])
print(a)
type(a)
a.dtype

[2 3 4]


dtype('int64')

In [134]:
# define with datatype
age = np.array([43,25,26], dtype=np.int8)
print(age)
# 0-255 - 8-bit

[43 25 26]


In [135]:
imag = np.array([[1, 2, 3, 4]], dtype=complex)
imag

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]])

In [140]:
# type(age)
# mat = np.arange(9).reshape((3,3))
c.shape
# mat.shape

(5,)

In [142]:
c.size
# imag.size

4

In [143]:
c.ndim

1

In [146]:
c.itemsize        # how many bytes to take for each element

x = np.array([2,3,3], dtype=np.int16)
x.itemsize
# 16 / 8 = 2
# 64 / 8 = 8

2

In [15]:
type(c)

numpy.ndarray

In [43]:
c.dtype

dtype('int64')

- 2D or 2 Dimensional

In [148]:
mat = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(mat)

"""
[
| 1 2 3 |
| 3 4 5 |
| 5 6 7 |

| 1 2 3 |
| 3 4 5 |
| 5 6 7 |
]
"""

[[1 2 3]
 [3 4 5]
 [5 6 7]]


'\n[\n| 1 2 3 |\n| 3 4 5 |\n| 5 6 7 |\n\n| 1 2 3 |\n| 3 4 5 |\n| 5 6 7 |\n]\n'

In [149]:
mat.shape, mat.size, mat.ndim

((3, 3), 9, 2)

In [150]:
# you can create ndimensional array

# 3-D means several 2d in [ [[],[]], [[],[]] ]

three_d = np.array([[[1,2],[2,3]],[[4,5],[7,9]]])
print(three_d)

[[[1 2]
  [2 3]]

 [[4 5]
  [7 9]]]


### Some special function for numpy array creation

- arange(start, end, step)
- ndarray.reshape(tuple)
- zeros()
- ones()
- empty()
- eye(), eye(n, [k])
- ones_like(), zeros_like()
- full(), full_like()

In [33]:
list(range(1, 20))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [151]:
seq = np.arange(1,23,3)
seq

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [36]:
even = np.arange(0,51,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [153]:
odd = np.arange(0,51,1)    # ??
odd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [156]:
# mat = np.arange(100).reshape((10,10))
# mat

np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
error = np.arange(25).reshape((25,1))  # ??

In [157]:
# numpy ones()

one = np.ones(10, dtype=np.int64)  # default data type np.float64
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [158]:
one.dtype

dtype('int64')

In [163]:
# tuple
# a = tuple([1,2,3])
# f,d,e = a

(1, 2, 3)

In [165]:
# np.function_name(  (1,2,4,5,6)  )

one = np.ones((3,4))
# np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
one.ndim       # ?? 2

In [ ]:
one.size       # ?? 12

In [ ]:
one.shape      # ?? (3,4)


In [172]:
one_3d = np.ones((2,2,2))     # (matrix_number, (row, col))       
one_3d

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [47]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
emty = np.empty(10)
emty

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Difference between np.empty() and np.zeros()**

`np.empty()`, unlike `np.zeros()`, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [173]:
empty_2d = np.empty((2,3))
empty_2d

1

In [51]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
eye = np.eye((3,3))  # ??

In [58]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
# difference between eye() and identity()

#np.eye() # has an extra parameter k
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [175]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [61]:
# zeors_like(), ones_like()

In [177]:
mat = np.arange(100).reshape(4,5,5)
mat

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [64]:
zeros_like = np.zeros_like(mat)
zeros_like

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [179]:
f = np.full((3,3), 100)
f

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [66]:
# asarray()
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
one.dtype

dtype('float64')

In [68]:
np.asarray(one, dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [81]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [82]:
np.random.randint(-3,3,(10,10))

array([[-3,  0,  1, -3, -3,  2,  0,  1, -3, -1],
       [ 0, -2, -3,  1,  0,  0,  2, -3,  1, -1],
       [-2,  2,  0, -3, -2,  1,  1,  1, -1, -3],
       [ 2, -2, -1, -1,  0,  0, -1,  2, -1, -3],
       [ 2,  0, -2, -2, -2,  1, -1,  1, -1,  2],
       [-2, -2, -3,  2,  2,  1, -3, -1, -1, -1],
       [ 2, -3, -1,  1, -2, -3,  1,  2, -3,  2],
       [ 2,  1,  1,  2,  1, -3,  1, -1,  1,  0],
       [ 2, -2, -3, -1,  0, -2,  0,  0,  0,  2],
       [ 2,  2, -3, -3, -3,  1,  2,  1, -2, -1]])

In [83]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

**np.copy()**

- My experience say's there is a problem. But at that case I cannot explain this. Next Day !!!!!

In [88]:
gray = np.ones((5,5))
gray

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
binary = gray[:2, :2]

In [90]:
gray = gray * 2

In [91]:
gray

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [92]:
binary

array([[1., 1.],
       [1., 1.]])

In [80]:
id(gray), id(binary)

(140603372113616, 140603372118032)

### Basic Numpy Operation

In [94]:
a = np.array([1,2,3])
b = np.ones(3)

a * b
# a - b
# a * b
# a // b
# a / b
# a ** 2

array([1., 2., 3.])

In [ ]:
b = np.ones(4)

a + b  # ??? 

### Slicing

In [110]:
a = np.random.randint(10, size=5)
a[0]

4

In [111]:
a[:2]

array([4, 2])

### Numpy ufunc or Universal Function

A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs. For detailed information on universal functions, see Universal functions (ufunc) basics.

Link: https://numpy.org/devdocs/reference/ufuncs.html 

In [97]:
a = np.random.randint(10, size=5)
a

array([4, 3, 7, 5, 5])

In [99]:
b = np.random.randint(10, size=5)
b

array([0, 5, 0, 1, 2])

In [100]:
a + b

array([4, 8, 7, 6, 7])

In [101]:
np.add(a, b)

array([4, 8, 7, 6, 7])

In [102]:
a ** 2

array([16,  9, 49, 25, 25])

In [103]:
a

array([4, 3, 7, 5, 5])

In [104]:
np.sin(a)

array([-0.7568025 ,  0.14112001,  0.6569866 , -0.95892427, -0.95892427])

In [105]:
np.log(a)

array([1.38629436, 1.09861229, 1.94591015, 1.60943791, 1.60943791])

In [107]:
### np.operation.accumulate()

np.add.accumulate(a)

array([ 4,  7, 14, 19, 24])

In [109]:
np.subtract.accumulate(a)

array([  4,   1,  -6, -11, -16])